### ISSUE TITLE
Error trying to launch `cli`- java.lang.NoSuchFieldError: IS_OSGI_RUNNING

### ISSUE THREAD

**Issue by iperdomo** [integratedmodelling/klab#43]
```
INFO: k.LAB v0.11.0 build VERSION_BUILD @VERSION_COMMIT booting...
Exception in thread "Thread-5" java.lang.NoSuchFieldError: IS_OSGI_RUNNING
	at org.eclipse.emf.ecore.impl.EPackageRegistryImpl.createGlobalRegistry(EPackageRegistryImpl.java:55)
	at org.eclipse.emf.ecore.EPackage$Registry.<clinit>(EPackage.java:75)
	at org.eclipse.xtext.testing.GlobalRegistries.initializeDefaults(GlobalRegistries.java:108)
	at org.integratedmodelling.klab.utils.xtext.KimInjectorProvider.<clinit>(KimInjectorProvider.java:24)
	at org.integratedmodelling.klab.engine.Engine.boot(Engine.java:517)
	at org.integratedmodelling.klab.engine.Engine.start(Engine.java:422)
	at org.integratedmodelling.klab.engine.Engine.start(Engine.java:388)
	at org.integratedmodelling.klab.clitool.CliRuntime.initialize(CliRuntime.java:43)
	at org.integratedmodelling.klab.clitool.console.TermConsole$1$2.run(TermConsole.java:280)
```

Other references with the same problem:

* https://github.com/metafacture/metafacture-fix/commit/b247128dff5c8dccdf4b2a18328f2caec14031f6
* https://github.com/eclipse/xtext-core/issues/2000

**Comment by iperdomo** [comment]
Solved with [2e980e2](https://github.com/integratedmodelling/klab/commit/2e980e233fefac59e060b8496a3504c9ddc55c07)
